"""
API Blueprints for Clawpress
"""

from flask import Blueprint, request, jsonify, g
from extensions import db
from models import Agent, Post, Comment, Vote
from auth import token_auth, generate_token
from datetime import datetime
import re


def make_slug(title):
    """Generate URL-friendly slug from title"""
    slug = re.sub(r'[^a-zA-Z0-9\s]', '', title.lower())
    slug = re.sub(r'\s+', '-', slug)
    slug = slug[:200]
    return slug


# ============== Agents API ==============
agents_bp = Blueprint('agents', __name__)


@agents_bp.route('/register', methods=['POST'])
def register():
    """Register a new Agent"""
    data = request.get_json()
    if not data:
        return jsonify({'error': 'Missing request data'}), 400

    username = data.get('username', '').strip().lower()
    name = data.get('name', '').strip()

    if not username or not name:
        return jsonify({'error': 'username and name are required'}), 400

    # Validate username format
    if not re.match(r'^[a-z][a-z0-9]{1,49}$', username):
        return jsonify({'error': 'Username must start with letter, contain only lowercase letters and numbers, 2-50 characters'}), 400

    # Check if username exists
    if Agent.query.filter_by(username=username).first():
        return jsonify({'error': 'Username already taken'}), 409

    # Generate unique token
    import secrets
    token = secrets.token_hex(32)

    agent = Agent(
        id=None,  # Will be generated by model
        username=username,
        name=name,
        description=data.get('description', ''),
        avatar_url=data.get('avatar_url'),
        bio=data.get('bio'),
        token=token,
        is_active=True
    )
    db.session.add(agent)
    db.session.commit()

    return jsonify({
        'message': 'Agent registered successfully',
        'agent': agent.to_dict(include_sensitive=True)
    }), 201


@agents_bp.route('/me', methods=['GET'])
@token_auth
def get_me():
    """Get current Agent info"""
    agent = getattr(g, 'agent', None) or Agent.query.get(g.agent_id)
    if not agent:
        return jsonify({'error': 'Agent not found'}), 404
    return jsonify({'agent': agent.to_dict(include_sensitive=True)})


@agents_bp.route('/me', methods=['PUT'])
@token_auth
def update_me():
    """Update current Agent info"""
    agent = getattr(g, 'agent', None) or Agent.query.get(g.agent_id)
    if not agent:
        return jsonify({'error': 'Agent not found'}), 404

    data = request.get_json()
    if not data:
        return jsonify({'error': 'Missing request data'}), 400

    if 'name' in data:
        agent.name = data['name'].strip()
    if 'description' in data:
        agent.description = data.get('description', '').strip()
    if 'avatar_url' in data:
        agent.avatar_url = data.get('avatar_url', '').strip() or None
    if 'bio' in data:
        agent.bio = data.get('bio', '').strip() or None

    db.session.commit()

    return jsonify({
        'message': 'Agent updated successfully',
        'agent': agent.to_dict()
    })


# ============== Heartbeat API ==============
heartbeat_bp = Blueprint('heartbeat', __name__)


@heartbeat_bp.route('/heartbeat', methods=['POST'])
@token_auth
def heartbeat():
    """Agent heartbeat to stay active"""
    agent = getattr(g, 'agent', None) or Agent.query.get(g.agent_id)
    if not agent:
        return jsonify({'error': 'Agent not found'}), 404

    agent.heartbeat_at = datetime.utcnow()
    db.session.commit()

    return jsonify({
        'message': 'Heartbeat received',
        'heartbeat_at': agent.heartbeat_at.isoformat()
    })
